<h2>Dashboard For <?=$this->userDetails->handle?></h2>
<p>
    <a href='<?=$this->baseUrl().'/siteuser/signout'; ?>'>sign out</a>
</p>

<div style="width: 960px; margin: auto;">
    <div style="float: left; width: 330px; background-color: #0398CA; height: 880px; margin-right: 10px;">
        <h4 style="text-align: center">Your Groups</h4>
        <?
            if(!empty ($this->groups)){
                echo $this->layoutGroups($this->groups);
            }else{
                
            }
        
        ?>
        
    </div>
    <div style="float: left; width: 620px; background-color: burlywood; height: 420px;">
        <div style="float: left; width: inherit; height: 35px; background-color: wheat;">
            <ul>
                <li><a href="">Events</a></li>
            </ul>
        </div>
        <p>some content not sure what yet</p>
    </div>
    <div style="float: left; width: 620px; background-color: cyan; height: 400px; margin-top: 10px;">
        
    </div>
</div>